name: Build

permissions: write-all

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        psabi: [default]

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 4096
        swap-size-mb: 512
        remove-dotnet: 'true'
        remove-android: 'true'

    - uses: actions/checkout@v3
    
  debian:
    name: Debian
    runs-on: ubuntu-latest
    container: docker.io/library/debian:testing
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Update repository
      run: |
        apt-get update -y
    - name: Install the basic dev packages
      run: apt-get install -y equivs curl git devscripts lintian build-essential automake autotools-dev
    - name: Config Files
      run: |
        debian/rules debian/control
        apt-get build-dep Linux
        
    - name: Install build dependencies
      run: |
        mk-build-deps -i -t "apt-get --yes" -r
    - name: Build Package
      run: |
        dpkg-buildpackage -b -nc -uc -j$(nproc)
    - name: Read Upload
      run: |
         mkdir artifact/
         # find build-sys -type f -name "*.iso" -exec mv {} artifact/ \;
         sudo mv ../*deb artifact/
            
    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: ${{ github.workspace }}/artifact/*
        compression-level: 9 # maximum compression
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`